//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_421_HusnutdinovFD.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationTournament
    {
        public int Id { get; set; }
        public Nullable<int> TournamentID { get; set; }
        public Nullable<int> TeamID { get; set; }
        public string Status { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Tournament Tournament { get; set; }
    }
}
